### ISSUE TITLE
settings button in main screen not working properly

### ISSUE THREAD

**Issue by LordBurtz** [susManager/app#8]
as stated,
settings only reachable by clicking the upper right corner, clicking in the middle doesn't trigger the switch

**Comment by Optinux** [comment]
I know about this but, sadly there isn't really a way to fix it since the code is identical to the other screens where it does, in fact, work flawlessly. My guess would be that maybe the ListView element is overlapping the button element in some way or another. This is very unlikely tho.

**Comment by LordBurtz** [comment]
fixed by commit `0812d36053da15076467170497de6c37e98f0934` by removing pointless, invisible button overlaying the icon used to go to the settings.fxml
